//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMoldApparadus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldTransaction
    {
        public long TransactionID { get; set; }
        public string Werk { get; set; }
        public long MoldID { get; set; }
        public long ApparadusID { get; set; }
        public string Quantity { get; set; }
        public string Usage { get; set; }
        public string UsingDescription { get; set; }
        public string Comment { get; set; }
        public int TransactionTypeNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LmDate { get; set; }
        public string LmBy { get; set; }
    }
}
