//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityInvalidRecord
    {
        public long qID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Shift { get; set; }
        public string FactoryID { get; set; }
        public string MachineID { get; set; }
        public string WorkorderNo { get; set; }
        public string Process { get; set; }
        public string MaterialName { get; set; }
        public string FirstItemQuality { get; set; }
        public string Status { get; set; }
        public string Hour { get; set; }
        public string Minute { get; set; }
        public Nullable<decimal> KeepQty { get; set; }
        public string KeepStartCartonID { get; set; }
        public string KeepEndCartonID { get; set; }
        public string Result { get; set; }
        public Nullable<decimal> WorkingTime { get; set; }
        public Nullable<decimal> ScrapQty { get; set; }
        public string Mold { get; set; }
        public Nullable<System.DateTime> LmTime { get; set; }
    }
}
