//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingHoursDescription
    {
        public long wID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Shift { get; set; }
        public string FactoryID { get; set; }
        public string MachineID { get; set; }
        public string WorkorderNo { get; set; }
        public string Process { get; set; }
        public Nullable<System.DateTime> EventDateTime { get; set; }
        public string MtTypeItems { get; set; }
        public string EventDescription { get; set; }
        public string DtTypeItems { get; set; }
        public string InvalidDescription { get; set; }
        public string Improve { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LmTime { get; set; }
    }
}
