//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearShiftConfig
    {
        public long yID { get; set; }
        public Nullable<System.DateTime> Version { get; set; }
        public string Year { get; set; }
        public string FactoryID { get; set; }
        public string ShiftID { get; set; }
        public string ShiftIndex { get; set; }
        public string DayNight { get; set; }
        public Nullable<System.DateTime> ShiftStart { get; set; }
        public Nullable<System.DateTime> ShiftEnd { get; set; }
    }
}
