//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTIPP0002B
    {
        public string WERKS { get; set; }
        public string AUFNR { get; set; }
        public string VORNR { get; set; }
        public string UVORN { get; set; }
        public string ARBPL { get; set; }
        public string KTEXT { get; set; }
        public string STEUS { get; set; }
        public string KTSCH { get; set; }
        public string LTXA1 { get; set; }
        public Nullable<decimal> MGVRG { get; set; }
        public Nullable<decimal> ASVRG { get; set; }
        public string MEINH { get; set; }
        public Nullable<decimal> BMSCH { get; set; }
        public Nullable<decimal> VGW01 { get; set; }
        public string VGE01 { get; set; }
        public Nullable<decimal> VGW02 { get; set; }
        public string VGE02 { get; set; }
        public Nullable<decimal> VGW03 { get; set; }
        public string VGE03 { get; set; }
        public Nullable<decimal> VGW04 { get; set; }
        public string VGE04 { get; set; }
        public Nullable<decimal> VGW05 { get; set; }
        public string VGE05 { get; set; }
        public Nullable<decimal> VGW06 { get; set; }
        public string VGE06 { get; set; }
        public string LOEKZ { get; set; }
        public string ERNAM_W { get; set; }
        public string CN_CREATE_DATE { get; set; }
        public string ERNAM_R { get; set; }
        public string CN_CHANGE_DATE { get; set; }
    }
}
