//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTIPP0003A
    {
        public long ID { get; set; }
        public string WERKS { get; set; }
        public string AUFNR { get; set; }
        public string VORNR { get; set; }
        public string ARBPL { get; set; }
        public string BUDAT { get; set; }
        public string ZMACHINE { get; set; }
        public string ZTYPE { get; set; }
        public Nullable<decimal> LMNGA { get; set; }
        public Nullable<decimal> XMNGA { get; set; }
        public string ZUNIT1 { get; set; }
        public Nullable<decimal> ZWORKHOUR { get; set; }
        public Nullable<decimal> ZEXWORKHOUR { get; set; }
        public string ZUNIT2 { get; set; }
        public Nullable<decimal> ZEMPNUMBER { get; set; }
        public Nullable<decimal> ZCOUNT { get; set; }
        public string RUECK { get; set; }
        public string RMZHL { get; set; }
        public string ZBDCDT { get; set; }
        public string ZSTATUS { get; set; }
        public string ZLOG { get; set; }
        public string CN_FLAG { get; set; }
        public string ERNAM_W { get; set; }
        public string CN_CREATE_DATE { get; set; }
        public string ERNAM_R { get; set; }
        public string CN_CHANGE_DATE { get; set; }
    }
}
