//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTIPP0004A
    {
        public string APPLY_NO { get; set; }
        public string AUFNR { get; set; }
        public string WERKS { get; set; }
        public string KTSCH { get; set; }
        public string LTXA1 { get; set; }
        public string MATNR { get; set; }
        public string CHARG { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public string LGORT { get; set; }
        public string BUDAT { get; set; }
        public string ZSTATUS { get; set; }
        public string ZLOG { get; set; }
        public string MJAHR { get; set; }
        public string MBLNR { get; set; }
        public string CN_FLAG { get; set; }
        public string ERNAM_W { get; set; }
        public string CN_CREATE_DATE { get; set; }
        public string ERNAM_R { get; set; }
        public string CN_CHANGE_DATE { get; set; }
    }
}
