//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLINQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTIPP0001A
    {
        public string MATNR { get; set; }
        public string WERKS { get; set; }
        public string MAKTX { get; set; }
        public string MEINS { get; set; }
        public string LGPRO { get; set; }
        public Nullable<decimal> NTGEW { get; set; }
        public Nullable<decimal> BRGEW { get; set; }
        public string GEWEI { get; set; }
        public Nullable<decimal> ZCARTONQTY { get; set; }
        public string ZLABELSIZE { get; set; }
        public string ZINNERTEXT { get; set; }
        public string ZSPEC { get; set; }
        public string ZTEMPERATURE { get; set; }
        public string ZORIGIN { get; set; }
        public string ZMATERIAL2 { get; set; }
        public string ZMATERIAL { get; set; }
        public string ZCOLOUR { get; set; }
        public string ZDESC { get; set; }
        public Nullable<decimal> ZMULTIPLE { get; set; }
        public string ZCBM { get; set; }
        public string ZUPC_CODE { get; set; }
        public string ZCGC_PART_NUMBER { get; set; }
        public string KUNNR { get; set; }
        public string NAME1 { get; set; }
        public string KDMAT { get; set; }
        public string POSTX { get; set; }
        public Nullable<decimal> ZFR1 { get; set; }
        public string ZCAVITY { get; set; }
        public string RBTXT { get; set; }
        public string LVORM { get; set; }
        public string ERNAM_W { get; set; }
        public string CN_CREATE_DATE { get; set; }
        public string ERNAM_R { get; set; }
        public string CN_CHANGE_DATE { get; set; }
    }
}
